### PR TITLE
:star2: adds support for formatting documents

### PR DESCRIPTION
**Pull request by AndCake**

### CODE REVIEW

**Comment by neurocyte** [comment]
Nice! Mostly works fine, but there is a small bug. Repeatedly pressing Alt-f causes previously re-formatted sections to be duplicated: (https://asciinema.org/a/hdvW5gAFAHvGkgmADn7wiK7N9)

**Comment by AndCake** [comment]
Great, thanks for the feedback :). I updated the PR to make sure the server is made aware of the re-formatted document. Can you check if it works on your side now? It appears functional on my side now.

**Comment by neurocyte** [comment]
Now I just get a Lua crash
```
Lua API error: main:408: attempt to call a non-function object
stack traceback:
        main:408: in function 'response'
        main:229: in main chunk
        [G]: ?
```

Re-opening the file shows that the formatting was applied before the crash.

**Comment by AndCake** [comment]
Sorry about that. Should now work fine.

**Comment by neurocyte** [comment]
Yep, works fine now. 👍

**Pull request merged**
